services:
  localdb:
    image: postgres:15.1
    ports:
      - "5432:5432"
    volumes:
      - .bd-read-system:/app-db-dumps
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=gg
      - POSTGRES_DB=readSystem

  testdb:
    image: postgres:15.1
    ports:
      - "5433:5432"
    volumes:
      - .bd-read-system-test:/app-db-dumps
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=gg
      - POSTGRES_DB=readSystemTest

volumes:
 bd-read-system:
 bd-read-system-test:
